"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue

        key, separator, value = line.partition('=')
        if not separator:
            continue

        key = key.strip()
        if not key or key in os.environ:
            continue

        os.environ[key] = value.strip().strip('"').strip("'")


_load_env_file(BASE_DIR / '.env')


def _parse_float_env(key: str, default: float) -> float:
    try:
        return float(os.getenv(key, default))
    except (TypeError, ValueError):
        return float(default)


def _parse_int_env(key: str, default: int) -> int:
    try:
        return int(float(os.getenv(key, default)))
    except (TypeError, ValueError):
        return int(default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY','')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # CSP 미들웨어 추가 (SecurityMiddleware 다음에 위치)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'bike'),
        'USER': os.getenv('POSTGRES_USER', 'bike_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'bike_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MAPBOX = {
    'ACCESS_TOKEN': os.getenv('MAPBOX_ACCESS_TOKEN', ''),
    'STYLE_URL': os.getenv('MAPBOX_STYLE_URL', 'mapbox://styles/mapbox/streets-v12'),
    'CENTER_LAT': _parse_float_env('MAPBOX_CENTER_LAT', 37.5665),
    'CENTER_LNG': _parse_float_env('MAPBOX_CENTER_LNG', 126.9780),
    'ZOOM': _parse_float_env('MAPBOX_ZOOM', 12),
}

# GraphHopper 서비스 접근 설정
GRAPHHOPPER = {
    'BASE_URL': os.getenv('GRAPHHOPPER_BASE_URL', 'http://localhost:8989'),
    'PROFILE': os.getenv('GRAPHHOPPER_PROFILE', 'bike'),
    'ALGORITHM': os.getenv('GRAPHHOPPER_ALGORITHM', 'round_trip'),
    'CH_DISABLE': os.getenv('GRAPHHOPPER_CH_DISABLE', 'true'),
    'AVERAGE_SPEED_KMH': _parse_float_env('GRAPHHOPPER_AVG_SPEED_KMH', 15.0),
    'REQUEST_TIMEOUT_SECONDS': _parse_int_env('GRAPHHOPPER_REQUEST_TIMEOUT_SECONDS', 15),
}

# Content Security Policy (CSP) 설정 (django-csp >= 4.0)
# https://django-csp.readthedocs.io/en/latest/configuration.html
_CONTENT_SECURITY_POLICY_DIRECTIVES = {
    'default-src': ("'self'",),
    'script-src': (
        "'self'",
        "'unsafe-inline'",  # Django admin과 일부 라이브러리를 위해 필요
        "'unsafe-eval'",    # 일부 라이브러리를 위해 필요
        "'strict-dynamic'",  # 동적 스크립트 로딩 허용
        'https://static.cloudflareinsights.com',
        'https://challenges.cloudflare.com',
        'https://bike.meloncaput.com',
        'https://api.mapbox.com',
    ),
    'style-src': (
        "'self'",
        "'unsafe-inline'",  # 인라인 스타일을 사용하는 경우 필요
        'https://bike.meloncaput.com',
        'https://api.mapbox.com',
    ),
    'img-src': (
        "'self'",
        'data:',
        'blob:',
        'https://bike.meloncaput.com',
        'https://api.mapbox.com',
        'https://*.tiles.mapbox.com',
    ),
    'font-src': (
        "'self'",
        'data:',
        'https://bike.meloncaput.com',
        'https://api.mapbox.com',
        'https://fonts.gstatic.com',
    ),
    'connect-src': (
        "'self'",
        'https://bike.meloncaput.com',
        'https://static.cloudflareinsights.com',
        'https://api.mapbox.com',
        'https://events.mapbox.com',
        'wss://*.cloudflare.com',
    ),
    'frame-src': ("'self'",),
    'object-src': ("'none'",),
    'base-uri': ("'self'",),
    'form-action': ("'self'",),
    'frame-ancestors': ("'none'",),
    'worker-src': ("'self'", 'blob:'),
}

CONTENT_SECURITY_POLICY = {
    'directives': _CONTENT_SECURITY_POLICY_DIRECTIVES,
}

if DEBUG:
    CONTENT_SECURITY_POLICY_REPORT_ONLY = {
        'directives': _CONTENT_SECURITY_POLICY_DIRECTIVES,
    }

# 추가 보안 헤더
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True  # X-Content-Type-Options: nosniff
X_FRAME_OPTIONS = 'DENY'  # X-Frame-Options: DENY

# Permissions Policy (이전의 Feature Policy)
PERMISSIONS_POLICY = {
    'geolocation': '()',  # 위치 정보 비활성화
    'microphone': '()',   # 마이크 비활성화
    'camera': '()',       # 카메라 비활성화
}

# 개발 환경에서는 CSP 보고서만 전송하고 차단하지 않음 (옵션)
CSP_REPORT_ONLY = DEBUG
